### ISSUE TITLE
Pointer-lists instead of parameter-lists in models with `sdfInputData`

### ISSUE THREAD

**Issue by JKRhb** [one-data-model/playground#50]
The [latest run](https://github.com/one-data-model/playground/runs/3136021849) of the CI script showed that there are models that are still using the 1.0 approach for modelling `sdfInputData`. To conform to the new version the `pointer-list` that is used in these models should be replaced with a `parameter-list`.

The models in question are:

* [sdfobject-genericlevel.sdf.json](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-genericlevel.sdf.json)
* [sdfobject-genericonoff.sdf.json](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-genericonoff.sdf.json)
* [sdfobject-genericdefaulttransitiontime.sdf.json](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-genericdefaulttransitiontime.sdf.json)
* [sdfobject-level.sdf.json](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-level.sdf.json)
* [sdfobject-onoff.sdf.json](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-onoff.sdf.json)

**Comment by JKRhb** [comment]
I also noticed that `parameter-list` is in fact not specified as a list or array but as a single `dataQualities` object. Is this intended or should the schema be changed in this regard?

Edit: I realized by now that this actually makes more sense. However, maybe removing the list part from this definition could be useful to avoid confusion.

**Comment by JKRhb** [comment]
Sorry, I discovered in the meantime that the main point of this issue will be resolved once #48 is merged.

**Comment by cabo** [comment]
Closed by #48
